apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpdserver
  labels: 
    k8s-app: http
spec:
  template:
    metadata: 
      labels:
        k8s-app: http
    spec:
      hostNetwork: true
      nodeSelector: 
        kubernetes.io/hostname:  osg.chic.nrp.internet2.edu
      containers:
      - name: httpd-server
        image: sfiligoi/kubernetes
        imagePullPolicy: Always
        #command: ["sh", "-c", "sleep infinity"]
        # command: ["/usr/sbin/httpd", "-DFOREGROUND"]
        env:
        - name: DATA2
          value: /edex
        volumeMounts:
          - name: config
            mountPath: /etc/httpd/conf.d
          - name: fs-store
            mountPath: /edex
      volumes:
        - name: config
          configMap: 
            name: http-configs 
        - name: fs-store
          flexVolume:
            driver: ceph.rook.io/rook
            fsType: ceph
            options:
              clusterNamespace: rook
              fsName: nautilusfs
              path: /edex
              mountUser: edex
              mountSecret: ceph-fs-secret          

